+nodejs

diff --git a/Dockerfile.base b/Dockerfile.base
--- a/Dockerfile.base
+++ b/Dockerfile.base
@@ -14,6 +14,7 @@ ARG TOOLS_TARBALL_URL
 ARG NVM_VERSION=0.39.1
 ARG NODE_VERSION=22.12.0
 ARG NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
+ARG NVM_PRIVATE_REPO=https://github.com/nvm-sh/nvm/archive/refs/tags
 
 ENV DEFAULT_GRADLE_VERSION=8.12
 ENV GRADLE_VERSIONS="4.10.3 5.6.4 6.9.4 7.6.1 8.8 8.12"
@@ -26,9 +27,7 @@ ENV SYFT_CHECK_FOR_APP_UPDATE=false
 ENV XEOL_DB_AUTO_UPDATE=false
 
 ENV NVM_DIR=/usr/local/nvm
-ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
-ENV NODE_PATH=$NVM_DIR/v$NODE_VERSION/lib/node_modules
-ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
+ENV PATH=$NVM_DIR:$PATH
 
 RUN echo "[global]" > /etc/pip.conf && \
     if [ -n "$GLOBAL_INDEX" ]; then \
@@ -197,18 +196,23 @@ RUN mkdir -p /home/prefect/.pip && \
       echo -e "[global]\nindex-url = ${GLOBAL_INDEX_URL}" > /home/prefect/.pip/pip.conf; \
     fi
 
-COPY nvm-sh-${NVM_VERSION}.zip /tmp/nvm.zip
+RUN wget --progress=dot:giga \
+    "${NVM_PRIVATE_REPO}/v${NVM_VERSION}.zip" \
+    -O /tmp/nvm.zip || { echo "NVM download failed"; exit 1; }
 
-RUN mkdir -p $NVM_DIR && \
-    unzip /tmp/nvm.zip -d $NVM_DIR && \
-    rm /tmp/nvm.zip
+RUN mkdir -p ${NVM_DIR} && \
+    unzip /tmp/nvm.zip -d ${NVM_DIR} && \
+    mv ${NVM_DIR}/nvm-${NVM_VERSION}/* ${NVM_DIR} && \
+    rm -rf ${NVM_DIR}/nvm-${NVM_VERSION} /tmp/nvm.zip
 
-
-RUN bash -c "source $NVM_DIR/nvm.sh && \
-    export NVM_NODEJS_ORG_MIRROR=$NVM_NODEJS_ORG_MIRROR && \
-    nvm install $NODE_VERSION && \
-    nvm alias default $NODE_VERSION && \
+RUN bash -c " \
+    source ${NVM_DIR}/nvm.sh && \
+    export NVM_NODEJS_ORG_MIRROR=${NVM_NODEJS_ORG_MIRROR} && \
+    nvm install ${NODE_VERSION} && \
+    nvm alias default ${NODE_VERSION} && \
     nvm use default"
+
+ENV PATH="${NVM_DIR}/versions/node/v${NODE_VERSION}/bin:${PATH}"
 
 RUN npm install -g yarn
 
